name: Update News

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-news.yml'
      - 'scripts/update_news.js'

permissions:
  contents: write

jobs:
  update-news:
    strategy:
      matrix:
        country: [us]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Fetch and Update News
        id: fetch-news
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: node scripts/update_news.js ${{ matrix.country }}

      - name: Commit and Push
        if: steps.fetch-news.outputs.should_commit == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Update news data (${{ matrix.country }})" || exit 0
          git pull --rebase
          git push
